### ISSUE TITLE
RealLifeCompletableFutureExample vs RealLifeWithoutCompletableFutureExample speed.

### ISSUE THREAD

**Issue by gidravlic** [manouti/completablefuture-examples#1]
Hello!

FYI

RealLifeCompletableFutureExample -> Took 5069 ms.
RealLifeWithoutCompletableFutureExample -> Took 15072 ms.
RealLifeWithoutCompletableFutureExample(with parallel stream) -> Took 5048 ms.

```java
        List<Car> cars = cars();
        cars.stream()
                .parallel()
                .forEach(car -> {
                    float rating = rating(car.getManufacturerId());
                    car.setRating(rating);
                });
        cars.forEach(System.out::println);
```

**Comment by manouti** [comment]
Thanks for sharing this! It's worth noting that the difference here is that with parallel streams we don't have the same level of control provided by CompletableFuture in terms of choosing the underlying thread executor. Also, parallel streams may use the main thread in addition to the common pool (so the main code will block for the parallel operation to finish).

Here's a nice related post: http://fahdshariff.blogspot.com/2016/06/java-8-completablefuture-vs-parallel.html
