### ISSUE TITLE
Cannot pass completeExceptionallyExample on JDK 8

### ISSUE THREAD

**Issue by mallim** [manouti/completablefuture-examples#2]
Hi

May I know how to revise the code to work on JDK 8?

Thanks

**Comment by manouti** [comment]
Created a new branch / tag that works under JDK 8:

https://github.com/manouti/completablefuture-examples/tree/java8

There were two changes:
- switch maven-compiler-plugin to use Java 8
- re-implement delayer executors that are equivalent to `CompletableFuture.delayedExecutor` (which is Java 9 and above)
